### ISSUE TITLE
ファイルが無いときに、アップロードを案内する

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#12]
現状、ここから何をしていいのかがわからない。

![スクリーンショット 2023-03-16 14 11 39](https://user-images.githubusercontent.com/1124652/225520941-ae24c629-18d4-4845-b0fa-3372eff7a682.png)

**期待する表示**

- ドラッグ・アンド・ドロップで、csv 他対応するファイルフォーマットをアップロードさせるUIが表示される

**Comment by champierre** [comment]
https://github.com/geolonia/opendata-editor/pull/24 で実装したのでクローズします。
