### ISSUE TITLE
MAPで編集する際、詳細が書かれたボックスのテキストが英語の場合はみ出ることがある

### ISSUE THREAD

**Issue by champierre** [geolonia/opendata-editor#16]
<img width="552" alt="スクリーンショット 2023-03-22 17 01 08" src="https://user-images.githubusercontent.com/8433892/226866221-c77af1f8-3f50-42e8-a65b-11c041338db8.png">
word-break: break-all; などで対応可能だと思います

**Comment by champierre** [comment]
https://github.com/geolonia/opendata-editor/pull/20 で修正しました。

**Comment by ShinichiNishikawa** [comment]
@marcofabrika  閉じて大丈夫です！

**Comment by champierre** [comment]
クローズします。
