### ISSUE TITLE
行の削除と追加をサポートする

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#2]
シート方式で編集しているとき、あるいは、地図の画面で、

* 新しいデータの行（地図ではポイント）を追加する
* いらなくなったデータの行（地図ではポイント）を削除する

ための仕組みが必要。

以下、考えたこと
---

* 位置情報を同時に登録させることを考えると、追加するUIは、地図画面にあるのがよいのではないか。あるいは、座標の列が空だった場合に、色の違う点が、たとえば高松市役所の上にあり、ユーザーに丸を動かさせて位置を指定させる必要がありそう

**Comment by champierre** [comment]
https://github.com/geolonia/opendata-editor/pull/18 で実装しました。

**Comment by champierre** [comment]
クローズします。
