### ISSUE TITLE
ユーザーが地図画面で位置を変更できる

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#3]
位置情報が誤っている場合、新規に追加する場合などに、ユーザーが座標を別の場所で取得することなく、地図上でポイントを指定したり、マーカーをドラッグ・アンド・ドロップで移動させる等、できる機能を作成する

**Comment by champierre** [comment]
@ShinichiNishikawa https://github.com/geolonia/opendata-editor/pull/21 で実装したのでクローズします。
