### ISSUE TITLE
初期画面で左上に余白ができ横にスクロールできる状態を修正する

### ISSUE THREAD

**Issue by naogify** [geolonia/opendata-editor#31]
![スクリーンショット 2023-07-14 11 21 49](https://github.com/geolonia/opendata-editor/assets/8760841/dfeebc1a-f8b4-44ac-bf92-0c6c3df35822)

**Comment by phanect** [comment]
@naogify これは「初期画面で左上に余白ができ横にスクロールできる状態になる」というバグの修正をする、という理解で良いでしょうか?
「初期画面で左上に余白ができ横にスクロールできる状態になる」ようにする、ということではないですよね?

**Comment by naogify** [comment]
@phanect 
> 「初期画面で左上に余白ができ横にスクロールできる状態になる」というバグの修正をする
はい、説明不足でしたが、スクロールできないようにしたいと言う趣旨でした。

**Comment by phanect** [comment]
@naogify 了解しました。ありがとうございます。
