### ISSUE TITLE
CSV 中に緯度経度として解釈できない数値が入っている場合に、データに含まれている点を包含するバウンディングボックスまでズームされない問題の修正

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#32]
2023/8/25 小川 @phanect 追記:

例えば下記のデータの場合、CSV 中に経度のデータとして 13409898 という値が含まれている。これはおそらく 134.09898 となっているべきで、小数点を入れ忘れているものと思われる。

https://geolonia.github.io/opendata-editor/?data=https://opendata.takamatsu-fact.com/aed_location/data.csv

このような小数点の入れ忘れにより、データを含むエリアが正しく判別されていないために発生している現象と思われる。

対応案としては以下の通りだが、このような対応方針で良いか相談したい。

- 明らかに緯度経度としておかしいデータがある場合はエラーを表示する
    - 地図とテーブルの間にエラーメッセージを表示する: 「n行目の経度 "13409898" は経度として適切な数値ではありません。正しい経度に書き換えて下さい」
    - 加えて、エラーのある行の背景色を赤か何かに変え、どこがエラーかわかりやすくする (※)
    - 加えて、できれば CSV データ読み込み時や経度の値が不適切な値に変更されたタイミングで、エラーのある行までスクロールする (※)
- その上で、地図上では明らかに緯度経度としておかしいデータを除外した上で fitBounds() を実行する
    - これはおそらく `@geolonia/embed` 側で対応すべきことと思われる

(※) のついているタスクの実装については #56 の実装完了後に行った方が効率的と思われる。

**Comment by phanect** [comment]
例えば下記のデータの場合、経度のデータとして 13409898 という値が含まれている。これはおそらく 134.09898 となっているべきで、小数点を入れ忘れているものと思われる。

https://geolonia.github.io/opendata-editor/?data=https://opendata.takamatsu-fact.com/aed_location/data.csv

このような小数点の入れ忘れにより、データを含むエリアが正しく判別されていないために発生している現象と思われる。

対応としては、明らかに緯度経度としておかしいデータを除外した上で fitBounds() を実行することが考えられるが、これはおそらく `@geolonia/embed` 側で対応すべきことと思われる。

**Comment by phanect** [comment]
@keichan34 

本文に以下の通り対応案を追記しましたが、このような方針でどうでしょうか?

> * 明らかに緯度経度としておかしいデータがある場合はエラーを表示する
>   
>   * 地図とテーブルの間にエラーメッセージを表示する: 「n行目の経度 "13409898" は経度として適切な数値ではありません。正しい経度に書き換えて下さい」
>   * 加えて、エラーのある行の背景色を赤か何かに変え、どこがエラーかわかりやすくする (※)
>   * 加えて、できれば CSV データ読み込み時や経度の値が不適切な値に変更されたタイミングで、エラーのある行までスクロールする (※)
> * その上で、地図上では明らかに緯度経度としておかしいデータを除外した上で fitBounds() を実行する
>   
>   * これはおそらく `@geolonia/embed` 側で対応すべきことと思われる

(※) のついているタスクの実装については #56 の前に行うと二度手間になってしまうため、#56 の実装完了後に行った方が良いかと思っています。

**Comment by keichan34** [comment]
そうですね、エラーがある行は明らかにしてあげた方が良さそうですね。
これembed APIのバグなんですね。。それは確かに、embedの方で修正した方が良さそう。

**Comment by phanect** [comment]
先に #56 を進める方向で確定

**Comment by phanect** [comment]
#67 で対応済みのためクローズ
