### ISSUE TITLE
ホーム画面アイコンを地図アイコンに差し替える

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#4]
以下のスクリーンショットで丸く囲んだ部分。地図アイコンにしたい。

![スクリーンショット 2023-03-13 19 10 37](https://user-images.githubusercontent.com/1124652/224671626-4b8c14a8-2ecc-4c90-998a-d30388baced1.png)

**Comment by champierre** [comment]
確認後、問題なければクローズをお願いします。 @ShinichiNishikawa

**Comment by ShinichiNishikawa** [comment]
ありがとうございます！
