### ISSUE TITLE
スタイルシートをコンポーネント外部に影響させないようにする

### ISSUE THREAD

**Issue by phanect** [geolonia/opendata-editor#41]
https://github.com/geolonia/opendata-editor/pull/36#issuecomment-1665216050 より継続

`<OpenDataEditor>` コンポーネント内のスタイルシートが、コンポーネント外部のスタイルシートと干渉しないようにする。

対応案としては以下:

- [styled-components](https://styled-components.com)
- BEM 化

小川としては、styled-components の方が近年は React ではよく使われており、スタイルシートのカプセル化の完全性も高そう (ランダム文字列を CSS クラス名につけてくれるため) であるため、styled-components の方が良いのではないかと考えている。
どのような方法で本 Issue に対応するか、相談したい。

**Comment by phanect** [comment]
@keichan34 上記、styled-components にするか、BEM にするか、あるいは他の方法で対応するか、ご相談したいです。

**Comment by keichan34** [comment]
styled-components にしましょうか。
