### ISSUE TITLE
データグリッドのライブラリーの選定・導入

### ISSUE THREAD

**Issue by phanect** [geolonia/opendata-editor#56]
現状のテーブルはユーザビリティが十分でない。
Excel や Google Spreadsheets のような UI が理想だが、下記のような問題がある。

- 編集ボタンを押してからでないとデータを編集できない
  - スプレッドシートならセルをダブルクリックして編集できる
- 右側に移動するのに一番下のスクロールバーを動かす必要がある
  - スプレッドシートならセルを選択した後→キーを押すことでも移動できる

これらを自前実装で改善するには工数がかかるため、外部コンポーネントライブラリーを用いて、既存のテーブルを置き換える。

# 実装時の考慮事項

- 現行実装の編集ボタンをクリックした際には、当該の行の値を変更できるようになるだけでなく、地図でマーカーを動かして、緯度経度のデータを編集することもできるようになる。編集ボタンを廃止し、データ編集はセルをダブルクリックして行う形で実装を考えているが、その場合、地図でのマーカー編集が行えることをユーザーにどのように知らせれば良いか、検討が必要である。
    - (案) スプレッドシートで初めて緯度経度のセルを選択した時に、「地図上のマーカーを動かすことでも緯度経度を編集できます」というポップアップを右下あたりに出す

# 候補ライブラリー

- https://github.com/adazzle/react-data-grid
    - [x] セルをダブルクリックして編集できるか? もしくは他に簡単な方法で編集できるか?
    - [x] 下のスクロールバーを動かさなくても左右に移動できるか? 例えばセルを選択して ← → キーを押すなどで移動できるか?
    - [x] 右クリックで行や列を削除できるか?
    - [x] 地図でマーカーを動かすことによる緯度経度のデータの編集はできるか?
        - [x] 地図でマーカーを動かした時に、それによる緯度経度の変化をスプレッドシート側に反映できるか? (JavaScript でスプレッドシートを編集する API が存在するか?)
            - `<DataGrid rows={rows} />` のように、`rows` 属性にデータを指定する。
        - [x] スプレッドシートで初めて緯度経度のセルを選択した時に、「地図上のマーカーを動かすことでも緯度経度を編集できます」というポップアップを出せるか? (特定のセルを選択したことを検知するイベントハンドラーが存在するか?)
            - `onSelectedRowsChange` イベントがそれのような気がする…
- https://github.com/denisraslov/react-spreadsheet-grid
    - [x] セルをダブルクリックして編集できるか? もしくは他に簡単な方法で編集できるか?
    - [ ] 下のスクロールバーを動かさなくても左右に移動できるか? 例えばセルを選択して ← → キーを押すなどで移動できるか?
        - 画面外にセルがはみ出るということはなく、全てのセルが画面内に収まるようにセルの横幅が小さくなる。 
    - [ ] 右クリックで行や列を削除できるか?
        - 自前実装しなければいけなさそう 
    - [x] 地図でマーカーを動かすことによる緯度経度のデータの編集はできるか?
        - [x] 地図でマーカーを動かした時に、それによる緯度経度の変化をスプレッドシート側に反映できるか? (JavaScript でスプレッドシートを編集する API が存在するか?)
            - `<Grid rows={rows} />` のように、`rows` 属性にデータを指定する。
        - [x] スプレッドシートで初めて緯度経度のセルを選択した時に、「地図上のマーカーを動かすことでも緯度経度を編集できます」というポップアップを出せるか? (特定のセルを選択したことを検知するイベントハンドラーが存在するか?)
            - `onCellClick` イベントで可能

**Comment by phanect** [comment]
https://zenn.dev/kazunori_kimura/scraps/9574500eb835ff を参考にライブラリーを比較し、react-data-grid と react-spreadsheet-grid を比較したが、react-data-grid の方が最終更新がより最近であること、react-spreadsheet-grid は一部要件を満たさないことから、ひとまず react-data-grid で進めてみることにした。

**Comment by phanect** [comment]
@keichan34 cc: @naogify 現状 opendata-editor にはテストがないので、今回の実装と同時にテストを導入したいのですが、テストツールの選定から始める必要があります。

以下のような方針でどうでしょうか?

- React Testing Library でできるところは React Testing Library でテストを実装する
  - ビルドツールに Vite を使っているので、テストフレームワークには Jest ではなく Vitest を利用する
- Visual Regression Test が必要な箇所は、Storybook + [Chromatic](https://www.chromatic.com) (SaaS だが無料枠内で足りるはず) を用いる

**Comment by phanect** [comment]
テスト、1個だけありました。
Jest で実行されているようですが、1個だけなので Vitest に移行してしまおうと思います。

**Comment by keichan34** [comment]
そうですね、テストはvitestにしましょう。
visual regression test はまだ入れる段階じゃない（ちょっとオーバスペック？）な気がするのですが、いかがでしょう？まだvitestとかでそれぞれのパーツをユニットテストっぽくする余裕がありそう

**Comment by phanect** [comment]
@keichan34 ありがとうございます。
では、テストフレームワークについては Vitest にしたいと思います。

VRT に関しては、昨日テスト項目を書き出してみたのですが、地図のレンダリングに関する部分はブラックボックステストにならざるを得ない気がしており、VRT でないとテストが難しいような気がしています。
Testing Library を使ったことがないのでまだあまりよくわかっていない部分があるのですが、このあたり React Testing Library でもできる余地はありそうでしょうか?

- セルをクリックで選択した時に地図でマップピンにズームされるか (VRT)
- セルを上下左右キーで移動した時に地図でマップピンにズームされるか (VRT)
- セルを右クリックで選択した時に地図でマップピンにズームされるか (VRT)
- 行を1行選択した時に、地図でその行の対応するマップピンにズームされるか (VRT)
- 行を2行以上選択した時に、地図内にそれらの行に対応するマップピンが全て表示されるようにズームされるか (VRT, 行選択機能をなくす場合は不要)
- 「データを追加」ボタンを押した時に、一番下にデータが追加され、追加された行のセルが選択され、追加された行までデータグリッドがスクロールするか (RTL?)
- 「データを追加」ボタンを押した時に、現在の地図の中央にマップピンが追加されるか (VRT)
- ポイント (赤い丸) を押すことで、行が選択され、マップピンが立つか (VRT)
- マップピンを移動し、確認ダイアログでキャンセルを選んだ時に、マップピンが元の場所に戻るか (VRT)
- コンテキストメニューから上の行に挿入ができるか (RTL?)
- コンテキストメニューから下の行に挿入ができるか (RTL?)
- コンテキストメニューから行の削除ができるか (RTL?)
- データを正しくダウンロードできるか (入力したデータとダウンロードしたデータが一致しているか?) (E2E? RTL?)

※ RTL == React Testing Library

**Comment by phanect** [comment]
地図は本ライブラリーの変更有無に関わらず変わるので、VRT でうまく一致してくれないことが多いとのこと。
代替案として、地図のズームの数値を取得して期待通りの値になっているか確認するなど。
