### ISSUE TITLE
<title /> とfavicon の変更

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/opendata-editor#7]
HTML のタイトルタグの中身を設定したい。提案としては以下。

- 位置情報CSV編集ツール | Geolonia
- オープンデータ編集マップ | Geolonia
- `ファイル名` | Geolonia オープンデータエディター

favicon: 現状は React App のものになっているが差し替えたい。
https://maps.geolonia.com/favicon.ico でいいと思います。

**Comment by champierre** [comment]
オープンデータ編集マップ | Geolonia

を採用しました。確認後、問題なければクローズをお願いします。

**Comment by ShinichiNishikawa** [comment]
確認しました！
